version: '2'

services:
  web:
    image: nginx:stable
    restart: unless-stopped

    ports:
      - "8080:80"

    volumes:
      - "./app:/app"
      - "./nginx/config:/etc/nginx/conf.d:ro,Z"
      - "./nginx/logs:/var/log/nginx"

    links:
      - php

  php:
    image: php:7-fpm

    volumes:
      - "./app:/app"

  elasticsearch:
    image: elasticsearch:2.4.0
    command: "elasticsearch -Des.network.host=0.0.0.0"
    restart: unless-stopped

#    volumes:
#      - "./esdata:/usr/share/elasticsearch/data:Z"

    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    build: logstash/
    command: "logstash -f /etc/logstash/conf.d/logstash.conf"
    restart: unless-stopped

    volumes:
      - "./logstash/config:/etc/logstash/conf.d:ro,Z"
      - "./logstash/patterns:/opt/logstash/patterns:ro,Z"
      - "./logstash/nginx_template.json:/opt/logstash/nginx_template.json"

    volumes_from:
      - web

    ports:
      - "5000:5000"

    depends_on:
      - elasticsearch

  kibana:
    build: kibana/
    restart: unless-stopped

    volumes:
      - "./kibana/config:/opt/kibana/config:ro,Z"

    depends_on:
      - elasticsearch
      - kibana_bootstrap

    ports:
      - "5601:5601"

  kibana_bootstrap:
    build: kibana/bootstrap/

    volumes:
      - "./kibana/kibana-bootstrap.json:/opt/kibana/kibana-bootstrap.json"

    depends_on:
      - elasticsearch

  testerbot:
    build: testerbot/
    command: "web 80"
    depends_on:
      - web
